export const movies = [
  {
    adult: false,
    backdrop_path: "/5PQhNs4M3RxIqaNAdBI6mXlXyYh.jpg",
    genre_ids: [27, 14, 9648],
    id: 839436,
    original_language: "en",
    original_title: "Dragon Fury",
    overview:
      "A group of soldiers are taken to the mountains of Wales to investigate a strange beast.",
    popularity: 1854.392,
    poster_path:
      "https://image.tmdb.org/t/p/w500/6WcJ4cV2Y3gnTYp5zHu968TYmTJ.jpg",
    release_date: "2021-06-15",
    title: "Dragon Fury",
    video: false,
    vote_average: 6,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/vQ9YlITvVFdbFXYX6qwTNgIP85u.jpg",
    genre_ids: [16, 28],
    id: 843241,
    original_language: "en",
    original_title: "Luca",
    overview:
      "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    popularity: 951.238,
    poster_path:
      "https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
    release_date: "2021-06-17",
    title: "Luca",
    video: false,
    vote_average: 8,
    vote_count: 4757,
  },
  {
    adult: false,
    backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: "en",
    original_title: "Cruella",
    overview:
      "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
    popularity: 712.898,
    poster_path:
      "https://image.tmdb.org/t/p/w500/wToO8opxkGwKgSfJ1JK8tGvkG6U.jpg",
    release_date: "2021-05-26",
    title: "Cruella",
    video: false,
    vote_average: 8.3,
    vote_count: 5612,
  },
  {
    adult: false,
    backdrop_path: "/5PQhNs4M3RxIqaNAdBI6mXlXyYh.jpg",
    genre_ids: [27, 14, 9648],
    id: 8394436,
    original_language: "en",
    original_title: "Dragon Fury",
    overview:
      "A group of soldiers are taken to the mountains of Wales to investigate a strange beast.",
    popularity: 1854.392,
    poster_path: `https://upload.wikimedia.org/wikipedia/en/2/2a/Monsters_University_poster_3.jpg`,
    release_date: "2021-06-15",
    title: "monster university ",
    video: false,
    vote_average: 6,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/vQ9YlITvVFdbFXYX6qwTNgIP85u.jpg",
    genre_ids: [16, 28],
    id: 8432341,
    original_language: "en",
    original_title: "Luca",
    overview:
      "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    popularity: 951.238,
    poster_path:
      "https://www.indiaeducation.net/imagesvr_ce/7180/AAEAAQAAAAAAAAgHAAAAJDU0ZDYwNzNjLTMwZGYtNGU4NC05OTA0LWMyOWZkNDhjZDc3Yw.jpg",
    release_date: "2021-06-17",
    title: "Minions",
    video: false,
    vote_average: 8,
    vote_count: 4757,
  },
  {
    adult: false,
    backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
    genre_ids: [28, 12, 14],
    id: 5665255,
    original_language: "en",
    original_title: "Cruella",
    overview:
      "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
    popularity: 712.898,
    poster_path: "https://media2.vault.com/16976/coco.jpg",
    release_date: "2021-05-26",
    title: "COCO",
    video: false,
    vote_average: 8.3,
    vote_count: 5612,
  },
];
